### ISSUE TITLE
Question about numerical determiners trigger extraction

### ISSUE THREAD

**Issue by styx97** [nyu-mll/presupposition_dataset#1]
Should [this](https://github.com/nyu-mll/nope/blob/e543810498ab1fb00abb86f116f6bc7ccb4ad4ca/extraction_pipeline/numeric_determiners.py#L76) line be - 

`if child.tag_ == "CD" and child.dep_ == "nummod":` in place of `if child.tag_ == "CD" and token.dep_ == "nummod":` ? Seems like there might be a typo.

**Comment by Alicia-Parrish** [comment]
Hi. I just wanted to let you know that we're looking into this. Our initial sense is that `child.dep_ == "nummod"` should work (as you suggest), but we've confirmed that the types of sentences that would have been affected if the script had a mistake are, in fact, included in the corpus (sentences with phrases like "all three pigs"). So we're still looking into this and will get back to you soon.

**Comment by sebschu** [comment]
Hi, I now looked into this in more detail and this indeed seems to be a typo and I fixed it -- sorry about that!

**Comment by styx97** [comment]
Thanks @sebschu! Liked the paper!
